config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  devise_scope :user do
    authenticated :user do
      root to: 'categories#index', as: :authenticated_root
    end

    unauthenticated :user do
      root to: 'splash#splash', as: :unauthenticated_root
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # root to: 'categories#index'

  resources :categories, only: %i[index new create destroy] do
    resources :payments, only: %i[index new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_payments, dependent: :destroy
  has_many :payments, through: :category_payments

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount
    payments.sum(:amount)
  end
end

app/models/category_payment.rb
class CategoryPayment < ApplicationRecord
  belongs_to :payment
  belongs_to :category

  validates :category, presence: true
  validates :payment, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_payments
  has_many :categories, through: :category_payments

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :payments, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, unless: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories.includes(:payments).order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @categorie = Category.new(categorie_params)
    @categorie.user = current_user
    if @categorie.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new, status: 422
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to categories_path, notice: "Deleted group: #{category.name}"
  end

  private

  def categorie_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @category = Category.includes(:payments).find(params[:category_id])
    @payments = @category.payments.order(created_at: :desc)
  end

  def new
    @categories = current_user.categories.all
    @transaction = Payment.new
  end

  def create
    payment = Payment.create(name: params[:transaction][:name], amount: params[:transaction][:amount],
                             author: current_user)

    category_ids = params[:transaction][:category_ids] || [] # Handle the case when no categories are selected

    category_ids.each do |category_id|
      category = Category.find_by(id: category_id) # Use find_by to avoid raising an exception if category is not found
      next unless category

      CategoryPayment.create(payment:, category:)
    end

    if payment.valid?
      redirect_to category_payments_path(params[:category_id]), notice: 'Transaction was successfully created.'
    else
      @categories = current_user.categories.all
      @transaction = payment # Assign the payment to @transaction for rendering the form with errors

      render :new, status: 422
    end
  end

  private

  def set_author
    @author = current_user
  end

  def categorie_params
    params.require(:transaction).permit(:id)
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!

  def splash; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<%= render 'shared/navbar', title: "#{@categories.name}" ,back_link: false %>


<div class = "groups_container">
  <% @categories.each do |category| %>
    <div class =  "group">
      <div class = "details_container">
      <img src="<%= category.icon %>" alt="group Icon" class="group-icon">
      <div class="text">
        <h2><%= category.name %></h2>
        <h4>$<%= category.total_amount %></h4>
        </div>
      </div>
      <p class="date"><%= "#{category.created_at.day} #{category.created_at.strftime("%b")} #{category.created_at.year}" %></p>
      <ul class = "group_actions">
      <li><button><%= link_to "View Transactions", category_payments_path(category), class: 'button' %></button></li>
      <li><%= button_to "Remove", category_path(category), data: {
      confirm: "Are you sure you want to delete: #{category.name}?",
    }, method: :delete, class: 'remove-btn', id: "remove_btn-#{category.id}" %></li>
    </ul>
    </div>
  <% end %>
</div>

<div class="group_btn">
  <%= link_to "Add New Category", new_category_path, class: 'add-btn' %>
</div>

app/views/categories/new.html.erb
<%= render 'shared/navbar', back_link: categories_path, title: "New Group" %>
<%= form_with(model: @category, url: categories_path, method: :post, class: "add-form") do |form| %>
  <h1 class="form-title">Add a new Group</h1>

  <!-- Display error messages if there are any -->
  <% if @errors %>
    <div class="error-message">
      <% @errors.each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
  <% end %>

  <div class="form-fields">
    <div class="field">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control", placeholder: "Name of group" %>
    </div>

    <div class="field">
      <%= form.label :icon, class: "form-label" %>
      <%= form.url_field :icon, class: "form-control", placeholder: "url" %>
    </div>
  </div>

  <%= form.submit "Save", class: 'submit-btn' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/payments/index.html.erb
<%= render 'shared/navbar', title:"#{@payments.name}", back_link: categories_path %>


<div class = "transaction_group">
  <h2><%= @category.name %></h2>
  <h2>$<%= @category.total_amount %></h2>
</div>

<div class = "transactions_container">
  <% @payments.each do |payment| %>
    <div class = "transaction_details">
      <div class = "transaction  details_container">
      <img src="https://png.pngtree.com/png-vector/20190130/ourlarge/pngtree-various-goods-and-cars-png-image_643136.jpg" />
      <div class="text-records">
        <h2><%= payment.name %></h2>
        <h3>$<%= payment.amount %></h3>
        </div>
      </div>
      <p><%= "#{payment.created_at.day} #{payment.created_at.strftime("%b")} #{payment.created_at.year}" %></p>
    </div>
  <% end %>

  <% if @payments.empty? %>
    <div class="no_content">
      <p>No transactions available yet!</p>
    </div>
  <% end %>
</div>

<div class="group_btn">
    <%= link_to 'Add New Transaction', new_category_payment_path(@category), class: 'add-btn' %>
</div>

app/views/payments/new.html.erb
<%= render 'shared/navbar', back_link: category_payments_path, title: "New Transaction" %>

<%= form_with model: @transaction, url: category_payments_path, method: :post, scope: :transaction do |form| %>
  <h1 class="form_title">Add a new Transaction</h1>

<div class="form-fields">
  <div class="field">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
    <% if @transaction.errors.has_key?(:name) %>
        <p class="error-message"><%= @transaction.errors[:name].first %></p>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :amount, class: "form-label" %>
    <%= form.number_field :amount, class: "form-control" %>
    <% if @transaction.errors.has_key?(:amount) %>
        <p class="error-message"><%= @transaction.errors[:amount].first %></p>
      <% end %>
  </div>

  <div class="field">
  <%= form.label :categories, class: "form-label" %>
  <%= form.collection_select :category_ids, @categories, :id, :name, {}, { multiple: true, class: 'form-select', required: true, aria_label: "Disabled select example" } %>
   
  <% if @transaction.errors.has_key?(:category_ids) %>
    <p class="error-message"><%= @transaction.errors[:category_ids].first %></p>
  <% end %>
</div>

  <div class='form-container'>
   <%= form.submit "Save", class: "submit-btn1" %>
  
  </div>

<% end %>

app/views/shared/_navbar.html.erb
<header class="main-header">
  <% if back_link %>
    <a href="<%= back_link %>" class="icon-btn">
      <i class="fa fa-arrow-left fa-lg"></i>
    </a>
  <% else %>
    <!-- Add a button to trigger the offcanvas menu -->
      <button type="button" class="icon-btn" id="toggleMenu">
    <i class="fa fa-bars"></i>
  </button>
  <% end %>
  <h1><%= title.upcase %></h1>
  <% if user_signed_in? %>
    <%= button_to destroy_user_session_path, method: :delete, class: "icon text-end" do %>
      <i class="fa fa-user"></i> Logout
    <% end %>
  <% elsif controller_name != 'sessions' %>
    <%= link_to new_user_session_path, class: "icon text-end" do %>
      <div>Next</div>
    <% end %>
  <% else %>
    <%= link_to new_user_registration_path, class: "icon text-end" do %>
      <i class="fa fa-user-plus"></i>
    <% end %>
  <% end %>
</header>

<% if user_signed_in? %>
<div class="offcanvas" id="offcanvasMenu">
      <button type="button" class="close-btn" id="closeMenu" aria-label="Close">x</button>
    <div class="offcanvas-header">
      <h2 class="offcanvas-title" id="sidebarLabel">Budget App</h2>
    </div>
    <div class="offcanvas-body">
      <div class="profile">
        <span>User: <%= current_user.name.upcase %></span>
      </div>
      <div class="actions">
     <i class="fa fa-plus-circle" aria-hidden="true"> <%= link_to "Create Group", new_category_path, class: "action" %></i>
        <hr>
      </div>
    </div>
  </div>
<% end %>

<script>
  document.getElementById('toggleMenu').addEventListener('click', function() {
    document.getElementById('offcanvasMenu').classList.toggle('show');
  });

  document.getElementById('closeMenu').addEventListener('click', function() {
    document.getElementById('offcanvasMenu').classList.remove('show');
  });
</script>

app/views/splash/splash.html.erb
<div class="main-container">
<div class = "container splash_screen">
  <h1>My Budget App</h1>
</div>

<div class = "registration_container">
  <%= link_to 'LOG IN', new_user_session_path, class: 'btn' %>
  <%= link_to 'SIGN UP', new_user_registration_path, class: 'btn splash-login' %>
</div>
</div>